const CONFIG = {
  levels: ['A1'],
  defaultLevel: 'A1',
  cases: [
    { id: 'nominative', label: 'Nominative', level: 'A1' },
    { id: 'instrumental', label: 'Instrumental', level: 'A1' },
    { id: 'mixed', label: 'Mixed', level: 'A1' },
  ],
  themes: [
    { id: 'all', label: 'All' },
    { id: 'rodzina', label: 'Family' },
    { id: 'zawody', label: 'Professions' },
    { id: 'jedzenie', label: 'Food' },
    { id: 'miejsca', label: 'Places' },
    { id: 'kolory', label: 'Colors' },
    { id: 'ludzie', label: 'People' },
    { id: 'zwierzeta', label: 'Animals' },
    { id: 'przedmioty', label: 'Objects' },
    { id: 'uczucia', label: 'Feelings' },
    { id: 'nature', label: 'Nature' },
  ],
  exerciseCounts: [5, 10, 20, 30, 50, 100],
  defaultExerciseCount: 20,
  exercisesPerCase: 20,
  masteryThreshold: 5,
  streakThreshold: 3,
  storageKeys: {
    nounMastery: 'polishclass_noun_mastery',
    adjMastery: 'polishclass_adj_mastery',
  },
}
